/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lexus.glb src/components/Lexus2.jsx 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2012-lexus-lfa-patrol-ff487de5fab54916b152eaef4c9dd36b
Title: 2012 Lexus LFA - Patrol
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Lexus(props) {
  const { nodes, materials } = useGLTF("/models/lexus.glb");

  // State lưu màu xe
  const [carColor, setCarColor] = useState("#ff3366");
  return (
    <group {...props} dispose={null}>
      <group scale={0.9}>
        <mesh geometry={nodes.COPM_Tire_Highcar_lexus_lfa_2012_Mesh_lod0_tire_0.geometry} material={materials.tire} />
        <mesh geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Rim_High_rim_0.geometry} material={materials.material} />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Opaque_AluminiumSmooth_High_ALUM_0.geometry}
          material={materials.ALUM}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Lightcluster_High_Light_Map_0.geometry}
          material={materials.Light_Map}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_LicensePlate_High_plate_0.geometry}
          material={materials.plate}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Internal_Engine_High_internal_0.geometry}
          material={materials.internal}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Badges_High_Badges_0.geometry}
          material={materials.Badges}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_BrakeDisc_High_breaks_0.geometry}
          material={materials.breaks}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Caliper_High_calipers_0.geometry}
          material={materials.calipers}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Chassis_High_chassis_0.geometry}
          material={materials.chassis}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GlassColor_Orange_High_orange_glass_0.geometry}
          material={materials.orange_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GlassColor_Orange_High_red_glass_0.geometry}
          material={materials.red_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GrilleA_High_griller_A_0.geometry}
          material={materials.griller_A}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GrilleB_High_grille_B_0.geometry}
          material={materials.grille_B}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CarbonA_High_carbon_0.geometry}
          material={materials.carbon}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_light_glaass_0.geometry}
          material={materials.light_glaass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_Windows_0.geometry}
          material={materials.Windows}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_orange_glass_0.geometry}
          material={materials.orange_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_LightRefracted_High_REF_0.geometry}
          material={materials.material_17}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_InternalTiled_High_carbon_0.geometry}
          material={materials.carbon}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Paint_Metal_High_LIV_0.geometry}
          material={materials.material_18}
          material-color={carColor} //← Đổi màu dynamic
          onClick={(e) => {
            e.stopPropagation(); // Ngăn event bubbling
            setCarColor((prev) => (prev === "#ff3366" ? "#3366ff" : "#ff3366"));
          }}
          onPointerOver={(e) => {
            e.stopPropagation();
            document.body.style.cursor = "pointer"; // Đổi cursor thành hand
          }}
          onPointerOut={(e) => {
            document.body.style.cursor = "auto";
          }}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CopProps_High_COPProps_0.geometry}
          material={materials.COPProps}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CopLights_High_copL_0.geometry}
          material={materials.copL}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_WindowSurround_High_glass_surr_0.geometry}
          material={materials.glass_surr}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_WindowSurround_High_mirror_0.geometry}
          material={materials.mirror}
        />
        <mesh
          geometry={nodes.emissM_Internal_Engine_Highcar_lexus_lfa_2012_Mesh_lod0_emiss_int_0.geometry}
          material={materials.emiss_int}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/lexus.glb");
