/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useMemo, useRef, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";

export function Lexus(props) {
  const { nodes, materials } = useGLTF("/models/lexus.glb");

  // 🎨 Array màu xe
  const CAR_COLORS = useMemo(
    () => ["#ff3366", "#3366ff", "#33ff66", "#ffcc33", "#cc33ff", "#ffffff", "#111111", "#ff6633"],
    [],
  );

  const [colorIndex, setColorIndex] = useState(null);
  const currentCarColor = colorIndex === null ? undefined : CAR_COLORS[colorIndex];

  const handleCarClick = (e) => {
    e.stopPropagation();
    setColorIndex((prev) => (prev === null ? 0 : (prev + 1) % CAR_COLORS.length));
  };

  // 💡 Ref cho đèn để làm hiệu ứng nhấp nháy nhẹ
  const headlightRef = useRef();

  // Pulsing đơn giản: intensity dao động 1.5 ~ 2.0
  useLayoutEffect(() => {
    let frame;
    const animate = () => {
      const t = Date.now() * 0.002;
      if (headlightRef.current?.material) {
        headlightRef.current.material.emissiveIntensity = 1.5 + Math.sin(t) * 0.3;
      }
      frame = requestAnimationFrame(animate);
    };
    animate();
    return () => cancelAnimationFrame(frame);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group scale={1.3}>
        {/* --- Mesh cơ bản --- */}
        <mesh geometry={nodes.COPM_Tire_Highcar_lexus_lfa_2012_Mesh_lod0_tire_0.geometry} material={materials.tire} />
        <mesh geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Rim_High_rim_0.geometry} material={materials.material} />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Opaque_AluminiumSmooth_High_ALUM_0.geometry}
          material={materials.ALUM}
        />

        {/* --- 🎯 ĐÈN TRƯỚC: Emissive + Pulsing --- */}
        <mesh
          ref={headlightRef}
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Lightcluster_High_Light_Map_0.geometry}
          material={materials.Light_Map}
          material-emissive="#ffffff" // 🔦 Màu phát sáng: trắng
          material-emissiveIntensity={1.5} // 💡 Độ sáng (1.0 ~ 3.0)
        />

        {/* Đèn phụ (kính đèn) - cũng làm sáng */}
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_LightRefracted_High_REF_0.geometry}
          material={materials.material_17}
          material-emissive="#ffffff"
          material-emissiveIntensity={1}
        />

        {/* --- Các mesh khác giữ nguyên --- */}
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_LicensePlate_High_plate_0.geometry}
          material={materials.plate}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Internal_Engine_High_internal_0.geometry}
          material={materials.internal}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Badges_High_Badges_0.geometry}
          material={materials.Badges}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_BrakeDisc_High_breaks_0.geometry}
          material={materials.breaks}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Caliper_High_calipers_0.geometry}
          material={materials.calipers}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Chassis_High_chassis_0.geometry}
          material={materials.chassis}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GlassColor_Orange_High_orange_glass_0.geometry}
          material={materials.orange_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GlassColor_Orange_High_red_glass_0.geometry}
          material={materials.red_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GrilleA_High_griller_A_0.geometry}
          material={materials.griller_A}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_GrilleB_High_grille_B_0.geometry}
          material={materials.grille_B}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CarbonA_High_carbon_0.geometry}
          material={materials.carbon}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_light_glaass_0.geometry}
          material={materials.light_glaass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_Windows_0.geometry}
          material={materials.Windows}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_Window_High_orange_glass_0.geometry}
          material={materials.orange_glass}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_InternalTiled_High_carbon_0.geometry}
          material={materials.carbon}
        />

        {/* --- 🎨 THÂN XE: Đổi màu khi click --- */}
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Paint_Metal_High_LIV_0.geometry}
          material={materials.material_18}
          material-color={currentCarColor}
          onClick={handleCarClick}
          onPointerOver={(e) => {
            e.stopPropagation();
            document.body.style.cursor = "pointer";
          }}
          onPointerOut={(e) => {
            document.body.style.cursor = "auto";
          }}
        />

        {/* --- Mesh còn lại --- */}
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CopProps_High_COPProps_0.geometry}
          material={materials.COPProps}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_CopLights_High_copL_0.geometry}
          material={materials.copL}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_WindowSurround_High_glass_surr_0.geometry}
          material={materials.glass_surr}
        />
        <mesh
          geometry={nodes.COPcar_lexus_lfa_2012_Mesh_lod0M_Glass_WindowSurround_High_mirror_0.geometry}
          material={materials.mirror}
        />
        <mesh
          geometry={nodes.emissM_Internal_Engine_Highcar_lexus_lfa_2012_Mesh_lod0_emiss_int_0.geometry}
          material={materials.emiss_int}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/lexus.glb");
